
import { GoogleGenAI, Type, Chat } from "@google/genai";
import type { QuizAnswers, ScentProfile, ChatMessage, Perfume } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
let chatInstance: Chat | null = null;

const scentProfileSchema = {
  type: Type.OBJECT,
  properties: {
    profileTitle: {
      type: Type.STRING,
      description: 'یک عنوان خلاقانه و شاعرانه برای شخصیت بویایی کاربر، مانند "معمار رویاها" یا "روح آزاد جنگل".',
    },
    profileDescription: {
      type: Type.STRING,
      description: 'یک توصیف جذاب و دقیق از پروفایل بویایی کاربر که شخصیت و ترجیحات او را بر اساس تحلیل روانشناختی منعکس می‌کند.',
    },
    personalityTraits: {
        type: Type.ARRAY,
        items: { type: Type.STRING },
        description: 'یک لیست از ۴ کلمه کلیدی که ابعاد شخصیتی کاربر را توصیف می‌کند (مثلاً: درونگرا، شهودی، منطقی، ساختارگرا).',
    },
    recommendedNotes: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: 'لیستی از ۳ تا ۵ نت کلیدی بویایی که برای این پروفایل مناسب است.',
    },
    perfumes: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          name: { type: Type.STRING, description: 'نامی خلاقانه و لوکس برای عطر پیشنهادی.' },
          notes: { type: Type.STRING, description: 'لیست نت‌های اصلی عطر با کاما از هم جدا شده.' },
          description: { type: Type.STRING, description: 'توصیفی احساسی و تصویری از عطر که حس و حال آن را منتقل می‌کند.' },
          visualTheme: { type: Type.STRING, description: 'یک عبارت کوتاه برای توصیف تم بصری عطر، مثلا "یک کتابخانه دنج با شومینه" یا "ساحل مدیترانه‌ای در غروب آفتاب".' }
        },
        required: ['name', 'notes', 'description', 'visualTheme']
      },
    },
  },
  required: ['profileTitle', 'profileDescription', 'personalityTraits', 'recommendedNotes', 'perfumes'],
};

function formatAnswersForPrompt(answers: QuizAnswers): string {
    let formatted = "پاسخ‌های کاربر به تست روانشناسی به این شرح است:\n";
    for (const [key, value] of Object.entries(answers)) {
        formatted += `- ${key}: ${value}\n`;
    }
    return formatted;
}

export const generateScentProfile = async (answers: QuizAnswers): Promise<ScentProfile> => {
  const prompt = `
    شما یک "روانشناس رایحه" و متخصص برندینگ برای برند لوکس "addaperfume" هستید.
    وظیفه شما تحلیل پاسخ‌های کاربر به یک تست شخصیت‌شناسی است تا پروفایل شخصیتی او را بر اساس مدل‌های روانشناسی (مانند MBTI) کشف کنید.
    
    ابتدا، پاسخ‌ها را تحلیل کرده و تمایلات شخصیتی کاربر را در چهار بعد اصلی مشخص کنید:
    ۱. منبع انرژی: درونگرا (I) یا برونگرا (E)
    ۲. نحوه درک اطلاعات: حسی (S) یا شهودی (N)
    ۳. سبک تصمیم‌گیری: منطقی (T) یا احساسی (F)
    ۴. رویکرد به زندگی: ساختارگرا (J) یا ادراکی (P)

    سپس، بر اساس این تحلیل عمیق، یک "پروفایل بویایی" منحصر به فرد ایجاد کنید.
    - یک عنوان خلاقانه برای پروفایل بسازید.
    - ۴ کلمه کلیدی که ابعاد شخصیتی او را خلاصه می‌کند، لیست کنید.
    - یک توصیف دقیق بنویسید که چگونه این ویژگی‌های شخصیتی به دنیای رایحه‌ها ترجمه می‌شوند.
    - در نهایت، ۳ عطر مفهومی از کالکشن خیالی "addaperfume" که کاملاً با این پروفایل مطابقت دارند، ابداع و پیشنهاد دهید.
    برای هر عطر، یک نام، لیستی از نت‌ها، یک توصیف احساسی و یک تم بصری ارائه دهید.
    
    ${formatAnswersForPrompt(answers)}
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: scentProfileSchema,
      },
    });

    const jsonString = response.text;
    const profile = JSON.parse(jsonString);

    // Basic validation
    if (!profile.profileTitle || !profile.perfumes || profile.perfumes.length === 0) {
      throw new Error("Invalid response structure from AI.");
    }

    return profile;
  } catch (error) {
    console.error("Error generating scent profile:", error);
    throw new Error("Failed to generate scent profile from AI.");
  }
};

export const generateImageForTheme = async (theme: string): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: `Create a luxurious, atmospheric, and photorealistic image representing this scent theme: "${theme}". Focus on mood and elegance.`,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '4:3',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error(`Error generating image for theme "${theme}":`, error);
    throw new Error("Failed to generate image from AI.");
  }
};

const singlePerfumeSchema = {
    type: Type.OBJECT,
    properties: {
      name: { type: Type.STRING, description: 'نامی خلاقانه و لوکس برای عطر پیشنهادی.' },
      notes: { type: Type.STRING, description: 'لیست نت‌های اصلی عطر با کاما از هم جدا شده.' },
      description: { type: Type.STRING, description: 'توصیفی احساسی و تصویری از عطر که حس و حال آن را منتقل می‌کند و توضیح می‌دهد چرا برای این شخصیت در این موقعیت مناسب است.' },
      visualTheme: { type: Type.STRING, description: 'یک عبارت کوتاه برای توصیف تم بصری عطر، مثلا "یک میز کار مدرن با نور ملایم" یا "یک باغ مخفی در مه صبحگاهی".' }
    },
    required: ['name', 'notes', 'description', 'visualTheme']
};

export const generateJourneyPerfume = async (profile: ScentProfile, journey: string): Promise<Perfume> => {
    const prompt = `
      شما یک "روانشناس رایحه" و متخصص برندینگ برای برند لوکس "addaperfume" هستید.
      شخصیت کاربر قبلاً تحلیل شده و پروفایل او به این شرح است:
      - عنوان پروفایل: "${profile.profileTitle}"
      - توصیف شخصیت: "${profile.profileDescription}"
      - ویژگی‌های کلیدی: ${profile.personalityTraits.join(', ')}

      وظیفه شما این است که یک عطر مفهومی کاملاً جدید از کالکشن خیالی "addaperfume" برای یک موقعیت خاص طراحی کنید.
      موقعیت مورد نظر: "${journey}"

      عطری خلق کنید که کاملاً با شخصیت کاربر و نیازمندی‌های این موقعیت خاص هماهنگ باشد.
      در توضیحات عطر، حتماً توضیح دهید که چرا این ترکیب نت‌ها برای این شخصیت در این سناریو مناسب است.
    `;

    try {
        const response = await ai.models.generateContent({
          model: "gemini-2.5-flash",
          contents: prompt,
          config: {
            responseMimeType: "application/json",
            responseSchema: singlePerfumeSchema,
          },
        });
    
        const jsonString = response.text;
        const perfume = JSON.parse(jsonString) as Perfume;
    
        if (!perfume.name || !perfume.notes) {
          throw new Error("Invalid perfume structure from AI.");
        }
    
        return perfume;
      } catch (error) {
        console.error(`Error generating journey perfume for "${journey}":`, error);
        throw new Error("Failed to generate journey perfume from AI.");
      }
};

export const getChatInstance = (): Chat => {
    if (!chatInstance) {
        chatInstance = ai.chats.create({
            model: 'gemini-2.5-flash',
            config: {
                systemInstruction: `شما یک مشاور عطر حرفه‌ای، خونگرم و آگاه برای برند "addaperfume" هستید. وظیفه شما راهنمایی کاربران برای پیدا کردن عطر ایده‌آلشان است. پاسخ‌های خود را کوتاه، مفید و دوستانه نگه دارید.`,
            },
        });
    }
    return chatInstance;
};

export const continueChat = async (history: ChatMessage[], message: string): Promise<string> => {
    try {
        const chat = getChatInstance();
        const response = await chat.sendMessage({ message });
        return response.text;
    } catch (error) {
        console.error("Error in chat:", error);
        return "متاسفانه در حال حاضر امکان پاسخگویی وجود ندارد. لطفاً بعداً دوباره تلاش کنید.";
    }
};